# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetable',
            name='auction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='direction_to_bid',
            field=models.CharField(default='', max_length=5),
        ),
    ]
