# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handnum', models.IntegerField()),
                ('suit', models.CharField(max_length=7)),
                ('value', models.CharField(max_length=7)),
                ('img_string', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('deal_id', models.AutoField(primary_key=True, serialize=False)),
                ('hand_string', models.CharField(max_length=52)),
                ('dealer', models.IntegerField()),
                ('vulnerability', models.IntegerField()),
                ('board_number', models.IntegerField()),
                ('in_play', models.BooleanField()),
                ('next_player', models.IntegerField(default=-1)),
                ('bridge_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BridgeTable')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('rand_bool', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leading_suit', models.CharField(blank=True, max_length=7)),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Deal')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='deal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Deal'),
        ),
        migrations.AddField(
            model_name='card',
            name='trick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Trick'),
        ),
    ]
