# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 20:16
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171109_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetable',
            name='contract',
            field=api.models.ContractField(default=''),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='declarer',
            field=models.CharField(default='', max_length=5),
        ),
    ]
