# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171115_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetable',
            name='trick_string',
            field=models.CharField(default='', max_length=13),
        ),
    ]
