# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 20:34
from __future__ import unicode_literals

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171110_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgetable',
            name='contract',
            field=api.models.ContractField(default=None, null=True),
        ),
    ]
