# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 04:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bridgetable_trick_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('east', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='east', to=settings.AUTH_USER_MODEL)),
                ('north', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='north', to=settings.AUTH_USER_MODEL)),
                ('south', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='south', to=settings.AUTH_USER_MODEL)),
                ('west', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='west', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bridgetable',
            name='east',
        ),
        migrations.RemoveField(
            model_name='bridgetable',
            name='north',
        ),
        migrations.RemoveField(
            model_name='bridgetable',
            name='south',
        ),
        migrations.RemoveField(
            model_name='bridgetable',
            name='west',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='seats',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='api.Seats'),
        ),
    ]
