# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171110_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridgetable',
            name='declarer',
        ),
    ]
