# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 03:41
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_bridgetable_declarer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetable',
            name='trick_taken',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bridgetable',
            name='deal',
            field=api.models.DealField(default=None, null=True),
        ),
    ]
