# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171113_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridgetable',
            old_name='trick_taken',
            new_name='tricks_taken',
        ),
    ]
