# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 21:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171218_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='bridgetable',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='east',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='north',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='south',
        ),
        migrations.RemoveField(
            model_name='seats',
            name='west',
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='east',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_as_east', to='api.Seat'),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='north',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_as_north', to='api.Seat'),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='south',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_as_south', to='api.Seat'),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='west',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_as_west', to='api.Seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Seats',
        ),
    ]
