# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-20 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171218_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bridgetable',
            old_name='total_tricks',
            new_name='level',
        ),
    ]
