# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bridgetable_trick'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetable',
            name='east',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='north',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='south',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='west',
            field=models.CharField(default='', max_length=100),
        ),
    ]
