# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171220_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='robot',
            field=models.BooleanField(default=False),
        ),
    ]
