# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_seat_robot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetable',
            name='phase',
            field=models.CharField(default='auction', max_length=100),
        ),
    ]
