# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171113_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BridgeTable'),
        ),
    ]
