# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seat',
            field=models.CharField(default='', max_length=5),
        ),
    ]
