# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171113_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridgetable',
            name='tricks_taken',
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='EW_tricks_taken',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='bridgetable',
            name='NS_tricks_taken',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
