# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171114_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridgetable',
            name='total_tricks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bridgetable',
            name='EW_tricks_taken',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bridgetable',
            name='NS_tricks_taken',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
