# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: handz-online:us-central1:handz-postgres-1

runtime_config:
  python_version: 3

env_variables:
    REDIS_HOST: redis-11325.c1.us-central1-2.gce.cloud.redislabs.com
    REDIS_PORT: 11325
    REDIS_PASSWORD: theworldisquiethere

# [END runtime]
