# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT mysite.wsgi

beta_settings:
    cloud_sql_instances: handz-online:us-central1:handz-postgres-1

runtime_config:
  python_version: 3

env_variables:
    REDIS_HOST: pub-redis-15180.us-west-2-1.1.ec2.garantiadata.com:
    REDIS_PORT: 15180
    REDIS_PASSWORD: theworldisquiethere

# [END runtime]
